app = 'floater-trainer'
primary_region = 'fra'

[build]
  image = 'ghcr.io/janbo208/floater-trainer:latest'

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
